JWT/Cookie basic integration
stanriders/circleforms pull request #18
Opened 2021-11-14 13:27 UTC by JustRoxy

2021-11-17 09:47 UTC, stanriders requested changes

2021-11-17 09:47 UTC, stanriders commented on backend/CircleForms/Controllers/Authorization/OAuth/OAuthController.cs
> +            var tokenHandler = new JwtSecurityTokenHandler();
I think this can be moved out to a separate `JWTService` so that we don't pollute auth controller with JWT creation

2021-11-17 09:47 UTC, stanriders commented on backend/CircleForms/Startup.cs
> +                        ValidateAudience = true,
Do we really care about issuer or audience? I think this can be cut out

2021-11-17 09:47 UTC, stanriders commented on backend/CircleForms/Startup.cs
> +                        ClockSkew = TimeSpan.Zero
Any reason to not use `DefaultClockSkew`?

2022-01-22 08:39 UTC, JustRoxy commented
The whole branch [jwt-tokens](https://github.com/stanriders/circleforms/tree/jwt-tokens) should be re-implemented

2022-01-22 08:39 UTC, closed without merging